<?php
//$db->debug = true;$codigoinscripcion = $_SESSION['numerodocumentosesion']; //mysql_select_db($database_sala, $sala);$query_parentesco = "select *from tipoestudiantefamiliaorder by 2";$parentesco = $db->Execute($query_parentesco);$totalRows_parentesco = $parentesco->RecordCount();$row_parentesco = $parentesco->FetchRow();$query_niveleducacion = "select *from niveleducacionorder by 2";$niveleducacion = $db->Execute($query_niveleducacion);$totalRows_niveleducacion = $niveleducacion->RecordCount();$row_niveleducacion = $niveleducacion->FetchRow();
$query_ciudad2 = "select *from ciudadorder by 3";$ciudad2 = $db->Execute($query_ciudad2);$totalRows_ciudad2 = $ciudad2->RecordCount();$row_ciudad2 = $ciudad2->FetchRow();
$query_formularios = "SELECT linkinscripcionmodulo,posicioninscripcionformulario,nombreinscripcionmodulo,im.idinscripcionmoduloFROM inscripcionformulario ip, inscripcionmodulo imWHERE ip.idinscripcionmodulo = im.idinscripcionmoduloAND ip.codigomodalidadacademica = '".$codigomodalidadacademicasesion."'AND ip.codigoestado LIKE '1%'order by posicioninscripcionformulario";$formularios = $db->Execute($query_formularios);$totalRows_formularios = $formularios->RecordCount();$row_formularios = $formularios->FetchRow();
$query_datosgrabados = "SELECT t.nombretipoestudiantefamilia, e.nombresestudiantefamilia, e.apellidosestudiantefamilia,
e.telefonoestudiantefamilia, e.ocupacionestudiantefamilia, e.idestudiantefamilia, e.idtipoestudiantefamiliaFROM estudiantefamilia e,tipoestudiantefamilia t,niveleducacion n WHERE e.idestudiantegeneral = '".$this->estudiantegeneral->idestudiantegeneral."'and e.idtipoestudiantefamilia = t.idtipoestudiantefamilia								 							 and e.idniveleducacion = n.idniveleducacion and e.codigoestado like '1%'order by e.idtipoestudiantefamilia";			  $datosgrabados = $db->Execute($query_datosgrabados);$totalRows_datosgrabados = $datosgrabados->RecordCount();$row_datosgrabados = $datosgrabados->FetchRow();if ($row_datosgrabados <> ""){ 
?>	       <table width="670px" border="1" cellpadding="1" cellspacing="0" bordercolor="#E9E9E9">                <tr id="trtitulogris">					<td>Parentesco</td>					<td>Nombre</td>					<!--  <td>Nivel de educación</td> -->					<!--  <td>Profesi&oacute;n</td> -->					<!-- <td>Dirección</td>  -->					<td>Ocupación</td>
                    <td>Teléfono</td>                </tr><?php 	do
	{ 
?>			    <tr>                     <td><?php echo $row_datosgrabados['nombretipoestudiantefamilia'];?></td>					 <td><?php echo $row_datosgrabados['nombresestudiantefamilia'];?> <?php echo $row_datosgrabados['apellidosestudiantefamilia'];?></td>                     <!-- <td><?php echo $row_datosgrabados['nombreniveleducacion'];?></td>  -->					 <!-- <td><?php echo $row_datosgrabados['profesionestudiantefamilia'];?></td>  -->					 <!-- <td><?php echo $row_datosgrabados['direccionestudiantefamilia'];?></td>  -->					 <td><?php echo $row_datosgrabados['ocupacionestudiantefamilia'];?></td>					 
					 <td><?php echo $row_datosgrabados['telefonoestudiantefamilia'];?></td>					 
					 <!-- <td><?php echo $row_datosgrabados['celularestudiantefamilia'];?></td>  -->					 			     </tr>			   <?php  	}
	while($row_datosgrabados = $datosgrabados->FetchRow());   		   			   ?>	    </table> 	   <?php}else if(!isset($_POST['inicial']) && !isset($_GET['inicial'])) {?><!-- <tr><td>Sin datos diligenciados</td></tr> --><?php}