/*
SQLyog Community- MySQL GUI v8.21 
MySQL - 5.1.36-community-log : Database - thhvsolic
*********************************************************************
*/

/*!40101 SET NAMES utf8 */;

/*!40101 SET SQL_MODE=''*/;

/*!40014 SET @OLD_UNIQUE_CHECKS=@@UNIQUE_CHECKS, UNIQUE_CHECKS=0 */;
/*!40014 SET @OLD_FOREIGN_KEY_CHECKS=@@FOREIGN_KEY_CHECKS, FOREIGN_KEY_CHECKS=0 */;
/*!40101 SET @OLD_SQL_MODE=@@SQL_MODE, SQL_MODE='NO_AUTO_VALUE_ON_ZERO' */;
/*!40111 SET @OLD_SQL_NOTES=@@SQL_NOTES, SQL_NOTES=0 */;
CREATE DATABASE /*!32312 IF NOT EXISTS*/`thhvsolic` /*!40100 DEFAULT CHARACTER SET latin1 */;

USE `thhvsolic`;

/*Table structure for table `tfacultad` */

DROP TABLE IF EXISTS `tfacultad`;

CREATE TABLE `tfacultad` (
  `IdFacultad` int(11) NOT NULL AUTO_INCREMENT,
  `Facultad` varchar(255) DEFAULT NULL,
  PRIMARY KEY (`IdFacultad`)
) ENGINE=MyISAM AUTO_INCREMENT=24 DEFAULT CHARSET=latin1;

/*Data for the table `tfacultad` */

insert  into `tfacultad`(`IdFacultad`,`Facultad`) values (9,'Facultad de Ciencias'),(10,'Facultad de Diseño Industrial'),(11,'Facultad de Enfermería'),(6,'Curso Básico'),(7,'Departamento de Bioética'),(8,'Facultad Administración de Empresas'),(12,'Facultad de Formación Musical'),(13,'Facultad de Medicina'),(14,'Facultad de Odontología'),(15,'Facultad de Psicología'),(16,'Facultad de Educación'),(17,'Programa de Arte Dramático'),(18,'Programa de Artes Plásticas'),(19,'Programa de Biología'),(20,'Programa de Ingeniería Ambiental'),(21,'Programa de Ingeniería de Sistemas'),(22,'Programa de Ingeniería Electrónica'),(23,'Programa de Ingeniería Industrial');

/*Table structure for table `tfacultad_copy` */

DROP TABLE IF EXISTS `tfacultad_copy`;

CREATE TABLE `tfacultad_copy` (
  `IdFacultad` int(11) NOT NULL AUTO_INCREMENT,
  `Facultad` varchar(255) DEFAULT NULL,
  PRIMARY KEY (`IdFacultad`)
) ENGINE=MyISAM AUTO_INCREMENT=24 DEFAULT CHARSET=latin1;

/*Data for the table `tfacultad_copy` */

insert  into `tfacultad_copy`(`IdFacultad`,`Facultad`) values (9,'Facultad de Ciencias'),(10,'Facultad de Diseño Industrial'),(11,'Facultad de Enfermería'),(6,'Curso Básico'),(7,'Departamento de Bioética'),(8,'Facultad Administración de Empresas'),(12,'Facultad de Formación Musical'),(13,'Facultad de Medicina'),(14,'Facultad de Odontología'),(15,'Facultad de Psicología'),(16,'Facultad de Educación'),(17,'Programa de Arte Dramático'),(18,'Programa de Artes Plásticas'),(19,'Programa de Biología'),(20,'Programa de Ingeniería Ambiental'),(21,'Programa de Ingeniería de Sistemas'),(22,'Programa de Ingeniería Electrónica'),(23,'Programa de Ingeniería Industrial');

/*Table structure for table `thvsolicit` */

DROP TABLE IF EXISTS `thvsolicit`;

CREATE TABLE `thvsolicit` (
  `CCHojaVi` bigint(30) NOT NULL COMMENT 'Cedula Hoja de vida',
  `Nombres` varchar(50) DEFAULT NULL,
  `Apellidos` varchar(50) DEFAULT NULL,
  `FechIngr` date DEFAULT NULL COMMENT 'Fecha de ingreso de la Hoja de Vida',
  `AreaAd1` varchar(200) DEFAULT NULL COMMENT 'Area administrativa que aspira 1',
  `AreaAd2` varchar(200) DEFAULT NULL COMMENT 'Area administrativa que aspira 2',
  `AreaAd3` varchar(200) DEFAULT NULL COMMENT 'Area administrativa que aspira 3',
  `AreaAd4` varchar(200) DEFAULT NULL COMMENT 'Area administrativa que aspira 4',
  `AreaAd5` varchar(200) DEFAULT NULL COMMENT 'Area administrativa que aspira 5',
  `Facult1` varchar(200) DEFAULT NULL COMMENT 'Facultad a la que aspira 1',
  `Facult2` varchar(200) DEFAULT NULL COMMENT 'Facultad a la que aspira 2',
  `Facult3` varchar(200) DEFAULT NULL COMMENT 'Facultad a la que aspira 3',
  `Facult4` varchar(200) DEFAULT NULL COMMENT 'Facultad a la que aspira 4',
  `Facult5` varchar(200) DEFAULT NULL COMMENT 'Facultad a la que aspira 5',
  `CargoAd1` varchar(200) DEFAULT NULL COMMENT 'Cargo administrativo que aspira 1',
  `CargoAd2` varchar(200) DEFAULT NULL COMMENT 'Cargo administrativo que aspira 2',
  `CargoAd3` varchar(200) DEFAULT NULL COMMENT 'Cargo administrativo que aspira 3',
  `CargoAd4` varchar(200) DEFAULT NULL COMMENT 'Cargo administrativo que aspira 4',
  `CargoAd5` varchar(200) DEFAULT NULL COMMENT 'Cargo administrativo que aspira 5',
  `Asignat1` varchar(200) DEFAULT NULL COMMENT 'Asignatura a la que aspira 1',
  `Asignat2` varchar(200) DEFAULT NULL COMMENT 'Asignatura a la que aspira 2',
  `Asignat3` varchar(200) DEFAULT NULL COMMENT 'Asignatura a la que aspira 3',
  `Asignat4` varchar(200) DEFAULT NULL COMMENT 'Asignatura a la que aspira 4',
  `Asignat5` varchar(200) DEFAULT NULL COMMENT 'Asignatura a la que aspira 5',
  `Sexo` varchar(20) DEFAULT NULL,
  `EstCivil` varchar(20) DEFAULT NULL,
  `Edad` int(11) DEFAULT NULL,
  `Nacional` varchar(30) DEFAULT NULL COMMENT 'Nacionalidad',
  `FechaNac` date DEFAULT NULL COMMENT 'Fecha de nacimiento',
  `LugarNac` varchar(50) DEFAULT NULL,
  `LibrMili` int(11) DEFAULT NULL COMMENT 'Libreta Mil. No',
  `Distrito` varchar(30) DEFAULT NULL COMMENT 'Distrito libreta militar',
  `Clase` varchar(20) DEFAULT NULL COMMENT 'Clase libreta militar',
  `FechaExp` date DEFAULT NULL COMMENT 'Fecha expedicion tarjeta militar',
  `Pasaport` varchar(30) DEFAULT NULL COMMENT 'No de pasaporte',
  `Profesion` varchar(100) DEFAULT NULL,
  `MatrProf` varchar(50) DEFAULT NULL COMMENT 'Matricula profesional No',
  `MatrDe` varchar(50) DEFAULT NULL COMMENT 'de donde es la Matricula prof',
  `FondPens` varchar(200) DEFAULT NULL COMMENT 'Fondo de pensiones',
  `EPS` varchar(200) DEFAULT NULL,
  `GrupoSan` varchar(3) DEFAULT NULL COMMENT 'Grupo sanguineo',
  `Direccion` varchar(200) DEFAULT NULL,
  `Barrio` varchar(50) DEFAULT NULL,
  `Telefono` varchar(50) DEFAULT NULL,
  `Celular` varchar(50) DEFAULT NULL,
  `Email` varchar(255) DEFAULT NULL,
  `AvisarA` varchar(255) DEFAULT NULL COMMENT 'En caso de Emergencia avisar a ',
  `TelAvis` varchar(50) DEFAULT NULL COMMENT 'Telefono persona a la que se avisa',
  `PadresVi` varchar(255) DEFAULT NULL COMMENT 'Nombres de padres vivos',
  `Conyuge` varchar(200) DEFAULT NULL COMMENT 'Nombre conyuge',
  `OcupCony` varchar(200) DEFAULT NULL COMMENT 'Ocupacion conyuge',
  `NoHijos` int(11) DEFAULT NULL COMMENT 'Numero de hijos',
  `NombHij1` varchar(200) DEFAULT NULL COMMENT 'Nombre hijo 1',
  `NombHij2` varchar(200) DEFAULT NULL COMMENT 'Nombre hijo 2',
  `NombHij3` varchar(200) DEFAULT NULL COMMENT 'Nombre hijo 3',
  `NombHij4` varchar(200) DEFAULT NULL COMMENT 'Nombre hijo 4',
  `NombHij5` varchar(200) DEFAULT NULL COMMENT 'Nombre hijo 5',
  `FeNaHij1` date DEFAULT NULL COMMENT 'Fecha nacimiento hijo 1',
  `FeNaHij2` date DEFAULT NULL COMMENT 'Fecha nacimiento hijo 2',
  `FeNaHij3` date DEFAULT NULL COMMENT 'Fecha nacimiento hijo 3',
  `FeNaHij4` date DEFAULT NULL COMMENT 'Fecha nacimiento hijo 4',
  `FeNaHij5` date DEFAULT NULL COMMENT 'Fecha nacimiento hijo 5',
  `IdenHij1` bigint(30) DEFAULT NULL COMMENT 'Identificacion hijo 1',
  `IdenHij2` bigint(30) DEFAULT NULL COMMENT 'Identificacion hijo 2',
  `IdenHij3` bigint(30) DEFAULT NULL COMMENT 'Identificacion hijo 3',
  `IdenHij4` bigint(30) DEFAULT NULL COMMENT 'Identificacion hijo 4',
  `IdenHij5` bigint(30) DEFAULT NULL COMMENT 'Identificacion hijo 5',
  `EdadHij1` int(11) DEFAULT NULL COMMENT 'Edad hijo 1',
  `EdadHij2` int(11) DEFAULT NULL COMMENT 'Edad hijo 2',
  `EdadHij3` int(11) DEFAULT NULL COMMENT 'Edad hijo 3',
  `EdadHij4` int(11) DEFAULT NULL COMMENT 'Edad hijo 4',
  `EdadHij5` int(11) DEFAULT NULL COMMENT 'Edad hijo 5',
  `UnEdHij1` varchar(20) DEFAULT NULL COMMENT 'años/meses hijo 1',
  `UnEdHij2` varchar(20) DEFAULT NULL COMMENT 'años/meses hijo 2',
  `UnEdHij3` varchar(20) DEFAULT NULL COMMENT 'años/meses hijo 3',
  `UnEdHij4` varchar(20) DEFAULT NULL COMMENT 'años/meses hijo 4',
  `UnEdHij5` varchar(20) DEFAULT NULL COMMENT 'años/meses hijo 5',
  `SexoHij1` varchar(20) DEFAULT NULL COMMENT 'Sexo hijo 1',
  `SexoHij2` varchar(20) DEFAULT NULL COMMENT 'Sexo hijo 2',
  `SexoHij3` varchar(20) DEFAULT NULL COMMENT 'Sexo hijo 3',
  `SexoHij4` varchar(20) DEFAULT NULL COMMENT 'Sexo hijo 4',
  `SexoHij5` varchar(20) DEFAULT NULL COMMENT 'Sexo hijo 5',
  `Titulo1` varchar(255) DEFAULT NULL COMMENT 'Estudios realizados - Titulo 1',
  `Titulo2` varchar(255) DEFAULT NULL COMMENT 'Estudios realizados - Titulo 2',
  `Titulo3` varchar(255) DEFAULT NULL COMMENT 'Estudios realizados - Titulo 3',
  `Titulo4` varchar(255) DEFAULT NULL COMMENT 'Estudios realizados - Titulo 4',
  `Titulo5` varchar(255) DEFAULT NULL COMMENT 'Estudios realizados - Titulo 5',
  `Titulo6` varchar(255) DEFAULT NULL COMMENT 'Estudios realizados - Titulo 6',
  `Titulo7` varchar(255) DEFAULT NULL COMMENT 'Estudios realizados - Titulo 7',
  `NivelT1` varchar(30) DEFAULT NULL COMMENT 'Nivel del Titulo 1',
  `NivelT2` varchar(30) DEFAULT NULL COMMENT 'Nivel del Titulo 2',
  `NivelT3` varchar(30) DEFAULT NULL COMMENT 'Nivel del Titulo 3',
  `NivelT4` varchar(30) DEFAULT NULL COMMENT 'Nivel del Titulo 4',
  `NivelT5` varchar(30) DEFAULT NULL COMMENT 'Nivel del Titulo 5',
  `NivelT6` varchar(30) DEFAULT NULL COMMENT 'Nivel del Titulo 6',
  `NivelT7` varchar(30) DEFAULT NULL COMMENT 'Nivel del Titulo 7',
  `Instit1` varchar(255) DEFAULT NULL COMMENT 'Institucion Titulo 1',
  `Instit2` varchar(255) DEFAULT NULL COMMENT 'Institucion Titulo 2',
  `Instit3` varchar(255) DEFAULT NULL COMMENT 'Institucion Titulo 3',
  `Instit4` varchar(255) DEFAULT NULL COMMENT 'Institucion Titulo 4',
  `Instit5` varchar(255) DEFAULT NULL COMMENT 'Institucion Titulo 5',
  `Instit6` varchar(255) DEFAULT NULL COMMENT 'Institucion Titulo 6',
  `Instit7` varchar(255) DEFAULT NULL COMMENT 'Institucion Titulo 7',
  `CiudaT1` varchar(50) DEFAULT NULL COMMENT 'Ciudad Titulo 1',
  `CiudaT2` varchar(50) DEFAULT NULL COMMENT 'Ciudad Titulo 2',
  `CiudaT3` varchar(50) DEFAULT NULL COMMENT 'Ciudad Titulo 3',
  `CiudaT4` varchar(50) DEFAULT NULL COMMENT 'Ciudad Titulo 4',
  `CiudaT5` varchar(50) DEFAULT NULL COMMENT 'Ciudad Titulo 5',
  `CiudaT6` varchar(50) DEFAULT NULL COMMENT 'Ciudad Titulo 6',
  `CiudaT7` varchar(50) DEFAULT NULL COMMENT 'Ciudad Titulo 7',
  `FechaT1` date DEFAULT NULL COMMENT 'Fecha terminacion Titulo 1',
  `FechaT2` date DEFAULT NULL COMMENT 'Fecha terminacion Titulo 2',
  `FechaT3` date DEFAULT NULL COMMENT 'Fecha terminacion Titulo 3',
  `FechaT4` date DEFAULT NULL COMMENT 'Fecha terminacion Titulo 4',
  `FechaT5` date DEFAULT NULL COMMENT 'Fecha terminacion Titulo 5',
  `FechaT6` date DEFAULT NULL COMMENT 'Fecha terminacion Titulo 6',
  `FechaT7` date DEFAULT NULL COMMENT 'Fecha terminacion Titulo 7',
  `EstudAct` varchar(2) DEFAULT NULL COMMENT 'Estudia actualmente SI/NO',
  `Program1` varchar(255) DEFAULT NULL COMMENT 'Estudia actualmente - Programa 1',
  `Program2` varchar(255) DEFAULT NULL COMMENT 'Estudia actualmente - Programa 2',
  `Program3` varchar(255) DEFAULT NULL COMMENT 'Estudia actualmente - Programa 3',
  `Program4` varchar(255) DEFAULT NULL COMMENT 'Estudia actualmente - Programa 4',
  `Program5` varchar(255) DEFAULT NULL COMMENT 'Estudia actualmente - Programa 5',
  `Semestr1` int(11) DEFAULT NULL COMMENT 'Semestre actual 1',
  `Semestr2` int(11) DEFAULT NULL COMMENT 'Semestre actual 2',
  `Semestr3` int(11) DEFAULT NULL COMMENT 'Semestre actual 3',
  `Semestr4` int(11) DEFAULT NULL COMMENT 'Semestre actual 4',
  `Semestr5` int(11) DEFAULT NULL COMMENT 'Semestre actual 5',
  `InstAct1` varchar(255) DEFAULT NULL COMMENT 'Institucion actual 1',
  `InstAct2` varchar(255) DEFAULT NULL COMMENT 'Institucion actual 2',
  `InstAct3` varchar(255) DEFAULT NULL COMMENT 'Institucion actual 3',
  `InstAct4` varchar(255) DEFAULT NULL COMMENT 'Institucion actual 4',
  `InstAct5` varchar(255) DEFAULT NULL COMMENT 'Institucion actual 5',
  `Horario1` varchar(20) DEFAULT NULL COMMENT 'Horario actual 1 - Diurno/Nocturno',
  `Horario2` varchar(20) DEFAULT NULL COMMENT 'Horario actual 2 - Diurno/Nocturno',
  `Horario3` varchar(20) DEFAULT NULL COMMENT 'Horario actual 3 - Diurno/Nocturno',
  `Horario4` varchar(20) DEFAULT NULL COMMENT 'Horario actual 4 - Diurno/Nocturno',
  `Horario5` varchar(20) DEFAULT NULL COMMENT 'Horario actual 5 - Diurno/Nocturno',
  `PrVirDi1` varchar(20) DEFAULT NULL COMMENT 'Presencial / Virtual /Distancia 1',
  `PrVirDi2` varchar(20) DEFAULT NULL COMMENT 'Presencial / Virtual /Distancia 2',
  `PrVirDi3` varchar(20) DEFAULT NULL COMMENT 'Presencial / Virtual /Distancia 3',
  `PrVirDi4` varchar(20) DEFAULT NULL COMMENT 'Presencial / Virtual /Distancia 4',
  `PrVirDi5` varchar(20) DEFAULT NULL COMMENT 'Presencial / Virtual /Distancia 5',
  `Software1` varchar(100) DEFAULT NULL COMMENT 'Que software o programas de Computación Maneja 1',
  `Software2` varchar(100) DEFAULT NULL COMMENT 'Que software o programas de Computación Maneja 2',
  `Software3` varchar(100) DEFAULT NULL COMMENT 'Que software o programas de Computación Maneja 3',
  `Software4` varchar(100) DEFAULT NULL COMMENT 'Que software o programas de Computación Maneja 4',
  `Software5` varchar(100) DEFAULT NULL COMMENT 'Que software o programas de Computación Maneja 5',
  `Idioma1` varchar(30) DEFAULT NULL COMMENT 'Que Idioma extranjero domina 1',
  `Idioma2` varchar(30) DEFAULT NULL COMMENT 'Que Idioma extranjero domina 2',
  `Idioma3` varchar(30) DEFAULT NULL COMMENT 'Que Idioma extranjero domina 3',
  `Idioma4` varchar(30) DEFAULT NULL COMMENT 'Que Idioma extranjero domina 4',
  `Idioma5` varchar(30) DEFAULT NULL COMMENT 'Que Idioma extranjero domina 5',
  `Entidad1` varchar(255) DEFAULT NULL COMMENT 'Experiencia laboral - Entidad 1',
  `Entidad2` varchar(255) DEFAULT NULL COMMENT 'Experiencia laboral - Entidad 2',
  `Entidad3` varchar(255) DEFAULT NULL COMMENT 'Experiencia laboral - Entidad 3',
  `Entidad4` varchar(255) DEFAULT NULL COMMENT 'Experiencia laboral - Entidad 4',
  `Entidad5` varchar(255) DEFAULT NULL COMMENT 'Experiencia laboral - Entidad 5',
  `Entidad6` varchar(255) DEFAULT NULL COMMENT 'Experiencia laboral - Entidad 6',
  `Entidad7` varchar(255) DEFAULT NULL COMMENT 'Experiencia laboral - Entidad 7',
  `CargoOc1` varchar(200) DEFAULT NULL COMMENT 'Experiencia laboral - Cargo 1',
  `CargoOc2` varchar(200) DEFAULT NULL COMMENT 'Experiencia laboral - Cargo 2',
  `CargoOc3` varchar(200) DEFAULT NULL COMMENT 'Experiencia laboral - Cargo 3',
  `CargoOc4` varchar(200) DEFAULT NULL COMMENT 'Experiencia laboral - Cargo 4',
  `CargoOc5` varchar(200) DEFAULT NULL COMMENT 'Experiencia laboral - Cargo 5',
  `CargoOc6` varchar(200) DEFAULT NULL COMMENT 'Experiencia laboral - Cargo 6',
  `CargoOc7` varchar(200) DEFAULT NULL COMMENT 'Experiencia laboral - Cargo 7',
  `TelEnti1` varchar(100) DEFAULT NULL COMMENT 'Telefonos Entidad 1',
  `TelEnti2` varchar(100) DEFAULT NULL COMMENT 'Telefonos Entidad 2',
  `TelEnti3` varchar(100) DEFAULT NULL COMMENT 'Telefonos Entidad 3',
  `TelEnti4` varchar(100) DEFAULT NULL COMMENT 'Telefonos Entidad 4',
  `TelEnti5` varchar(100) DEFAULT NULL COMMENT 'Telefonos Entidad 5',
  `TelEnti6` varchar(100) DEFAULT NULL COMMENT 'Telefonos Entidad 6',
  `TelEnti7` varchar(100) DEFAULT NULL COMMENT 'Telefonos Entidad 7',
  `DirEnti1` varchar(255) DEFAULT NULL COMMENT 'Direccion Entidad 1',
  `DirEnti2` varchar(255) DEFAULT NULL COMMENT 'Direccion Entidad 2',
  `DirEnti3` varchar(255) DEFAULT NULL COMMENT 'Direccion Entidad 3',
  `DirEnti4` varchar(255) DEFAULT NULL COMMENT 'Direccion Entidad 4',
  `DirEnti5` varchar(255) DEFAULT NULL COMMENT 'Direccion Entidad 5',
  `DirEnti6` varchar(255) DEFAULT NULL COMMENT 'Direccion Entidad 6',
  `DirEnti7` varchar(255) DEFAULT NULL COMMENT 'Direccion Entidad 7',
  `JefeInm1` varchar(100) DEFAULT NULL COMMENT 'Jefe Inmediato 1',
  `JefeInm2` varchar(100) DEFAULT NULL COMMENT 'Jefe Inmediato 2',
  `JefeInm3` varchar(100) DEFAULT NULL COMMENT 'Jefe Inmediato 3',
  `JefeInm4` varchar(100) DEFAULT NULL COMMENT 'Jefe Inmediato 4',
  `JefeInm5` varchar(100) DEFAULT NULL COMMENT 'Jefe Inmediato 5',
  `JefeInm6` varchar(100) DEFAULT NULL COMMENT 'Jefe Inmediato 6',
  `JefeInm7` varchar(100) DEFAULT NULL COMMENT 'Jefe Inmediato 7',
  `MotiRet1` varchar(255) DEFAULT NULL COMMENT 'Motivo Retiro 1',
  `MotiRet2` varchar(255) DEFAULT NULL COMMENT 'Motivo Retiro 2',
  `MotiRet3` varchar(255) DEFAULT NULL COMMENT 'Motivo Retiro 3',
  `MotiRet4` varchar(255) DEFAULT NULL COMMENT 'Motivo Retiro 4',
  `MotiRet5` varchar(255) DEFAULT NULL COMMENT 'Motivo Retiro 5',
  `MotiRet6` varchar(255) DEFAULT NULL COMMENT 'Motivo Retiro 6',
  `MotiRet7` varchar(255) DEFAULT NULL COMMENT 'Motivo Retiro 7',
  PRIMARY KEY (`CCHojaVi`)
) ENGINE=MyISAM DEFAULT CHARSET=latin1;

/*Data for the table `thvsolicit` */

/*Table structure for table `thvsolicit_copy` */

DROP TABLE IF EXISTS `thvsolicit_copy`;

CREATE TABLE `thvsolicit_copy` (
  `CCHojaVi` bigint(30) NOT NULL COMMENT 'Cedula Hoja de vida',
  `Nombres` varchar(50) DEFAULT NULL,
  `Apellidos` varchar(50) DEFAULT NULL,
  `FechIngr` date DEFAULT NULL COMMENT 'Fecha de ingreso de la Hoja de Vida',
  `AreaAd1` varchar(200) DEFAULT NULL COMMENT 'Area administrativa que aspira 1',
  `AreaAd2` varchar(200) DEFAULT NULL COMMENT 'Area administrativa que aspira 2',
  `AreaAd3` varchar(200) DEFAULT NULL COMMENT 'Area administrativa que aspira 3',
  `AreaAd4` varchar(200) DEFAULT NULL COMMENT 'Area administrativa que aspira 4',
  `AreaAd5` varchar(200) DEFAULT NULL COMMENT 'Area administrativa que aspira 5',
  `Facult1` varchar(200) DEFAULT NULL COMMENT 'Facultad a la que aspira 1',
  `Facult2` varchar(200) DEFAULT NULL COMMENT 'Facultad a la que aspira 2',
  `Facult3` varchar(200) DEFAULT NULL COMMENT 'Facultad a la que aspira 3',
  `Facult4` varchar(200) DEFAULT NULL COMMENT 'Facultad a la que aspira 4',
  `Facult5` varchar(200) DEFAULT NULL COMMENT 'Facultad a la que aspira 5',
  `CargoAd1` varchar(200) DEFAULT NULL COMMENT 'Cargo administrativo que aspira 1',
  `CargoAd2` varchar(200) DEFAULT NULL COMMENT 'Cargo administrativo que aspira 2',
  `CargoAd3` varchar(200) DEFAULT NULL COMMENT 'Cargo administrativo que aspira 3',
  `CargoAd4` varchar(200) DEFAULT NULL COMMENT 'Cargo administrativo que aspira 4',
  `CargoAd5` varchar(200) DEFAULT NULL COMMENT 'Cargo administrativo que aspira 5',
  `Asignat1` varchar(200) DEFAULT NULL COMMENT 'Asignatura a la que aspira 1',
  `Asignat2` varchar(200) DEFAULT NULL COMMENT 'Asignatura a la que aspira 2',
  `Asignat3` varchar(200) DEFAULT NULL COMMENT 'Asignatura a la que aspira 3',
  `Asignat4` varchar(200) DEFAULT NULL COMMENT 'Asignatura a la que aspira 4',
  `Asignat5` varchar(200) DEFAULT NULL COMMENT 'Asignatura a la que aspira 5',
  `Sexo` varchar(20) DEFAULT NULL,
  `EstCivil` varchar(20) DEFAULT NULL,
  `Edad` int(11) DEFAULT NULL,
  `Nacional` varchar(30) DEFAULT NULL COMMENT 'Nacionalidad',
  `FechaNac` date DEFAULT NULL COMMENT 'Fecha de nacimiento',
  `LugarNac` varchar(50) DEFAULT NULL,
  `LibrMili` int(11) DEFAULT NULL COMMENT 'Libreta Mil. No',
  `Distrito` varchar(30) DEFAULT NULL COMMENT 'Distrito libreta militar',
  `Clase` varchar(20) DEFAULT NULL COMMENT 'Clase libreta militar',
  `FechaExp` date DEFAULT NULL COMMENT 'Fecha expedicion tarjeta militar',
  `Pasaport` varchar(30) DEFAULT NULL COMMENT 'No de pasaporte',
  `Profesion` varchar(100) DEFAULT NULL,
  `MatrProf` varchar(50) DEFAULT NULL COMMENT 'Matricula profesional No',
  `MatrDe` varchar(50) DEFAULT NULL COMMENT 'de donde es la Matricula prof',
  `FondPens` varchar(200) DEFAULT NULL COMMENT 'Fondo de pensiones',
  `EPS` varchar(200) DEFAULT NULL,
  `GrupoSan` varchar(3) DEFAULT NULL COMMENT 'Grupo sanguineo',
  `Direccion` varchar(200) DEFAULT NULL,
  `Barrio` varchar(50) DEFAULT NULL,
  `Telefono` varchar(50) DEFAULT NULL,
  `Celular` varchar(50) DEFAULT NULL,
  `Email` varchar(255) DEFAULT NULL,
  `AvisarA` varchar(255) DEFAULT NULL COMMENT 'En caso de Emergencia avisar a ',
  `TelAvis` varchar(50) DEFAULT NULL COMMENT 'Telefono persona a la que se avisa',
  `PadresVi` varchar(255) DEFAULT NULL COMMENT 'Nombres de padres vivos',
  `Conyuge` varchar(200) DEFAULT NULL COMMENT 'Nombre conyuge',
  `OcupCony` varchar(200) DEFAULT NULL COMMENT 'Ocupacion conyuge',
  `NoHijos` int(11) DEFAULT NULL COMMENT 'Numero de hijos',
  `NombHij1` varchar(200) DEFAULT NULL COMMENT 'Nombre hijo 1',
  `NombHij2` varchar(200) DEFAULT NULL COMMENT 'Nombre hijo 2',
  `NombHij3` varchar(200) DEFAULT NULL COMMENT 'Nombre hijo 3',
  `NombHij4` varchar(200) DEFAULT NULL COMMENT 'Nombre hijo 4',
  `NombHij5` varchar(200) DEFAULT NULL COMMENT 'Nombre hijo 5',
  `FeNaHij1` date DEFAULT NULL COMMENT 'Fecha nacimiento hijo 1',
  `FeNaHij2` date DEFAULT NULL COMMENT 'Fecha nacimiento hijo 2',
  `FeNaHij3` date DEFAULT NULL COMMENT 'Fecha nacimiento hijo 3',
  `FeNaHij4` date DEFAULT NULL COMMENT 'Fecha nacimiento hijo 4',
  `FeNaHij5` date DEFAULT NULL COMMENT 'Fecha nacimiento hijo 5',
  `IdenHij1` bigint(30) DEFAULT NULL COMMENT 'Identificacion hijo 1',
  `IdenHij2` bigint(30) DEFAULT NULL COMMENT 'Identificacion hijo 2',
  `IdenHij3` bigint(30) DEFAULT NULL COMMENT 'Identificacion hijo 3',
  `IdenHij4` bigint(30) DEFAULT NULL COMMENT 'Identificacion hijo 4',
  `IdenHij5` bigint(30) DEFAULT NULL COMMENT 'Identificacion hijo 5',
  `EdadHij1` int(11) DEFAULT NULL COMMENT 'Edad hijo 1',
  `EdadHij2` int(11) DEFAULT NULL COMMENT 'Edad hijo 2',
  `EdadHij3` int(11) DEFAULT NULL COMMENT 'Edad hijo 3',
  `EdadHij4` int(11) DEFAULT NULL COMMENT 'Edad hijo 4',
  `EdadHij5` int(11) DEFAULT NULL COMMENT 'Edad hijo 5',
  `UnEdHij1` varchar(20) DEFAULT NULL COMMENT 'años/meses hijo 1',
  `UnEdHij2` varchar(20) DEFAULT NULL COMMENT 'años/meses hijo 2',
  `UnEdHij3` varchar(20) DEFAULT NULL COMMENT 'años/meses hijo 3',
  `UnEdHij4` varchar(20) DEFAULT NULL COMMENT 'años/meses hijo 4',
  `UnEdHij5` varchar(20) DEFAULT NULL COMMENT 'años/meses hijo 5',
  `SexoHij1` varchar(20) DEFAULT NULL COMMENT 'Sexo hijo 1',
  `SexoHij2` varchar(20) DEFAULT NULL COMMENT 'Sexo hijo 2',
  `SexoHij3` varchar(20) DEFAULT NULL COMMENT 'Sexo hijo 3',
  `SexoHij4` varchar(20) DEFAULT NULL COMMENT 'Sexo hijo 4',
  `SexoHij5` varchar(20) DEFAULT NULL COMMENT 'Sexo hijo 5',
  `Titulo1` varchar(255) DEFAULT NULL COMMENT 'Estudios realizados - Titulo 1',
  `Titulo2` varchar(255) DEFAULT NULL COMMENT 'Estudios realizados - Titulo 2',
  `Titulo3` varchar(255) DEFAULT NULL COMMENT 'Estudios realizados - Titulo 3',
  `Titulo4` varchar(255) DEFAULT NULL COMMENT 'Estudios realizados - Titulo 4',
  `Titulo5` varchar(255) DEFAULT NULL COMMENT 'Estudios realizados - Titulo 5',
  `Titulo6` varchar(255) DEFAULT NULL COMMENT 'Estudios realizados - Titulo 6',
  `Titulo7` varchar(255) DEFAULT NULL COMMENT 'Estudios realizados - Titulo 7',
  `NivelT1` varchar(30) DEFAULT NULL COMMENT 'Nivel del Titulo 1',
  `NivelT2` varchar(30) DEFAULT NULL COMMENT 'Nivel del Titulo 2',
  `NivelT3` varchar(30) DEFAULT NULL COMMENT 'Nivel del Titulo 3',
  `NivelT4` varchar(30) DEFAULT NULL COMMENT 'Nivel del Titulo 4',
  `NivelT5` varchar(30) DEFAULT NULL COMMENT 'Nivel del Titulo 5',
  `NivelT6` varchar(30) DEFAULT NULL COMMENT 'Nivel del Titulo 6',
  `NivelT7` varchar(30) DEFAULT NULL COMMENT 'Nivel del Titulo 7',
  `Instit1` varchar(255) DEFAULT NULL COMMENT 'Institucion Titulo 1',
  `Instit2` varchar(255) DEFAULT NULL COMMENT 'Institucion Titulo 2',
  `Instit3` varchar(255) DEFAULT NULL COMMENT 'Institucion Titulo 3',
  `Instit4` varchar(255) DEFAULT NULL COMMENT 'Institucion Titulo 4',
  `Instit5` varchar(255) DEFAULT NULL COMMENT 'Institucion Titulo 5',
  `Instit6` varchar(255) DEFAULT NULL COMMENT 'Institucion Titulo 6',
  `Instit7` varchar(255) DEFAULT NULL COMMENT 'Institucion Titulo 7',
  `CiudaT1` varchar(50) DEFAULT NULL COMMENT 'Ciudad Titulo 1',
  `CiudaT2` varchar(50) DEFAULT NULL COMMENT 'Ciudad Titulo 2',
  `CiudaT3` varchar(50) DEFAULT NULL COMMENT 'Ciudad Titulo 3',
  `CiudaT4` varchar(50) DEFAULT NULL COMMENT 'Ciudad Titulo 4',
  `CiudaT5` varchar(50) DEFAULT NULL COMMENT 'Ciudad Titulo 5',
  `CiudaT6` varchar(50) DEFAULT NULL COMMENT 'Ciudad Titulo 6',
  `CiudaT7` varchar(50) DEFAULT NULL COMMENT 'Ciudad Titulo 7',
  `FechaT1` date DEFAULT NULL COMMENT 'Fecha terminacion Titulo 1',
  `FechaT2` date DEFAULT NULL COMMENT 'Fecha terminacion Titulo 2',
  `FechaT3` date DEFAULT NULL COMMENT 'Fecha terminacion Titulo 3',
  `FechaT4` date DEFAULT NULL COMMENT 'Fecha terminacion Titulo 4',
  `FechaT5` date DEFAULT NULL COMMENT 'Fecha terminacion Titulo 5',
  `FechaT6` date DEFAULT NULL COMMENT 'Fecha terminacion Titulo 6',
  `FechaT7` date DEFAULT NULL COMMENT 'Fecha terminacion Titulo 7',
  `EstudAct` varchar(2) DEFAULT NULL COMMENT 'Estudia actualmente SI/NO',
  `Program1` varchar(255) DEFAULT NULL COMMENT 'Estudia actualmente - Programa 1',
  `Program2` varchar(255) DEFAULT NULL COMMENT 'Estudia actualmente - Programa 2',
  `Program3` varchar(255) DEFAULT NULL COMMENT 'Estudia actualmente - Programa 3',
  `Program4` varchar(255) DEFAULT NULL COMMENT 'Estudia actualmente - Programa 4',
  `Program5` varchar(255) DEFAULT NULL COMMENT 'Estudia actualmente - Programa 5',
  `Semestr1` int(11) DEFAULT NULL COMMENT 'Semestre actual 1',
  `Semestr2` int(11) DEFAULT NULL COMMENT 'Semestre actual 2',
  `Semestr3` int(11) DEFAULT NULL COMMENT 'Semestre actual 3',
  `Semestr4` int(11) DEFAULT NULL COMMENT 'Semestre actual 4',
  `Semestr5` int(11) DEFAULT NULL COMMENT 'Semestre actual 5',
  `InstAct1` varchar(255) DEFAULT NULL COMMENT 'Institucion actual 1',
  `InstAct2` varchar(255) DEFAULT NULL COMMENT 'Institucion actual 2',
  `InstAct3` varchar(255) DEFAULT NULL COMMENT 'Institucion actual 3',
  `InstAct4` varchar(255) DEFAULT NULL COMMENT 'Institucion actual 4',
  `InstAct5` varchar(255) DEFAULT NULL COMMENT 'Institucion actual 5',
  `Horario1` varchar(20) DEFAULT NULL COMMENT 'Horario actual 1 - Diurno/Nocturno',
  `Horario2` varchar(20) DEFAULT NULL COMMENT 'Horario actual 2 - Diurno/Nocturno',
  `Horario3` varchar(20) DEFAULT NULL COMMENT 'Horario actual 3 - Diurno/Nocturno',
  `Horario4` varchar(20) DEFAULT NULL COMMENT 'Horario actual 4 - Diurno/Nocturno',
  `Horario5` varchar(20) DEFAULT NULL COMMENT 'Horario actual 5 - Diurno/Nocturno',
  `PrVirDi1` varchar(20) DEFAULT NULL COMMENT 'Presencial / Virtual /Distancia 1',
  `PrVirDi2` varchar(20) DEFAULT NULL COMMENT 'Presencial / Virtual /Distancia 2',
  `PrVirDi3` varchar(20) DEFAULT NULL COMMENT 'Presencial / Virtual /Distancia 3',
  `PrVirDi4` varchar(20) DEFAULT NULL COMMENT 'Presencial / Virtual /Distancia 4',
  `PrVirDi5` varchar(20) DEFAULT NULL COMMENT 'Presencial / Virtual /Distancia 5',
  `Software1` varchar(100) DEFAULT NULL COMMENT 'Que software o programas de Computación Maneja 1',
  `Software2` varchar(100) DEFAULT NULL COMMENT 'Que software o programas de Computación Maneja 2',
  `Software3` varchar(100) DEFAULT NULL COMMENT 'Que software o programas de Computación Maneja 3',
  `Software4` varchar(100) DEFAULT NULL COMMENT 'Que software o programas de Computación Maneja 4',
  `Software5` varchar(100) DEFAULT NULL COMMENT 'Que software o programas de Computación Maneja 5',
  `Idioma1` varchar(30) DEFAULT NULL COMMENT 'Que Idioma extranjero domina 1',
  `Idioma2` varchar(30) DEFAULT NULL COMMENT 'Que Idioma extranjero domina 2',
  `Idioma3` varchar(30) DEFAULT NULL COMMENT 'Que Idioma extranjero domina 3',
  `Idioma4` varchar(30) DEFAULT NULL COMMENT 'Que Idioma extranjero domina 4',
  `Idioma5` varchar(30) DEFAULT NULL COMMENT 'Que Idioma extranjero domina 5',
  `Entidad1` varchar(255) DEFAULT NULL COMMENT 'Experiencia laboral - Entidad 1',
  `Entidad2` varchar(255) DEFAULT NULL COMMENT 'Experiencia laboral - Entidad 2',
  `Entidad3` varchar(255) DEFAULT NULL COMMENT 'Experiencia laboral - Entidad 3',
  `Entidad4` varchar(255) DEFAULT NULL COMMENT 'Experiencia laboral - Entidad 4',
  `Entidad5` varchar(255) DEFAULT NULL COMMENT 'Experiencia laboral - Entidad 5',
  `Entidad6` varchar(255) DEFAULT NULL COMMENT 'Experiencia laboral - Entidad 6',
  `Entidad7` varchar(255) DEFAULT NULL COMMENT 'Experiencia laboral - Entidad 7',
  `CargoOc1` varchar(200) DEFAULT NULL COMMENT 'Experiencia laboral - Cargo 1',
  `CargoOc2` varchar(200) DEFAULT NULL COMMENT 'Experiencia laboral - Cargo 2',
  `CargoOc3` varchar(200) DEFAULT NULL COMMENT 'Experiencia laboral - Cargo 3',
  `CargoOc4` varchar(200) DEFAULT NULL COMMENT 'Experiencia laboral - Cargo 4',
  `CargoOc5` varchar(200) DEFAULT NULL COMMENT 'Experiencia laboral - Cargo 5',
  `CargoOc6` varchar(200) DEFAULT NULL COMMENT 'Experiencia laboral - Cargo 6',
  `CargoOc7` varchar(200) DEFAULT NULL COMMENT 'Experiencia laboral - Cargo 7',
  `TelEnti1` varchar(100) DEFAULT NULL COMMENT 'Telefonos Entidad 1',
  `TelEnti2` varchar(100) DEFAULT NULL COMMENT 'Telefonos Entidad 2',
  `TelEnti3` varchar(100) DEFAULT NULL COMMENT 'Telefonos Entidad 3',
  `TelEnti4` varchar(100) DEFAULT NULL COMMENT 'Telefonos Entidad 4',
  `TelEnti5` varchar(100) DEFAULT NULL COMMENT 'Telefonos Entidad 5',
  `TelEnti6` varchar(100) DEFAULT NULL COMMENT 'Telefonos Entidad 6',
  `TelEnti7` varchar(100) DEFAULT NULL COMMENT 'Telefonos Entidad 7',
  `DirEnti1` varchar(255) DEFAULT NULL COMMENT 'Direccion Entidad 1',
  `DirEnti2` varchar(255) DEFAULT NULL COMMENT 'Direccion Entidad 2',
  `DirEnti3` varchar(255) DEFAULT NULL COMMENT 'Direccion Entidad 3',
  `DirEnti4` varchar(255) DEFAULT NULL COMMENT 'Direccion Entidad 4',
  `DirEnti5` varchar(255) DEFAULT NULL COMMENT 'Direccion Entidad 5',
  `DirEnti6` varchar(255) DEFAULT NULL COMMENT 'Direccion Entidad 6',
  `DirEnti7` varchar(255) DEFAULT NULL COMMENT 'Direccion Entidad 7',
  `JefeInm1` varchar(100) DEFAULT NULL COMMENT 'Jefe Inmediato 1',
  `JefeInm2` varchar(100) DEFAULT NULL COMMENT 'Jefe Inmediato 2',
  `JefeInm3` varchar(100) DEFAULT NULL COMMENT 'Jefe Inmediato 3',
  `JefeInm4` varchar(100) DEFAULT NULL COMMENT 'Jefe Inmediato 4',
  `JefeInm5` varchar(100) DEFAULT NULL COMMENT 'Jefe Inmediato 5',
  `JefeInm6` varchar(100) DEFAULT NULL COMMENT 'Jefe Inmediato 6',
  `JefeInm7` varchar(100) DEFAULT NULL COMMENT 'Jefe Inmediato 7',
  `MotiRet1` varchar(255) DEFAULT NULL COMMENT 'Motivo Retiro 1',
  `MotiRet2` varchar(255) DEFAULT NULL COMMENT 'Motivo Retiro 2',
  `MotiRet3` varchar(255) DEFAULT NULL COMMENT 'Motivo Retiro 3',
  `MotiRet4` varchar(255) DEFAULT NULL COMMENT 'Motivo Retiro 4',
  `MotiRet5` varchar(255) DEFAULT NULL COMMENT 'Motivo Retiro 5',
  `MotiRet6` varchar(255) DEFAULT NULL COMMENT 'Motivo Retiro 6',
  `MotiRet7` varchar(255) DEFAULT NULL COMMENT 'Motivo Retiro 7',
  PRIMARY KEY (`CCHojaVi`)
) ENGINE=MyISAM DEFAULT CHARSET=latin1;

/*Data for the table `thvsolicit_copy` */

/*Table structure for table `thvsolicit_copy2` */

DROP TABLE IF EXISTS `thvsolicit_copy2`;

CREATE TABLE `thvsolicit_copy2` (
  `CCHojaVi` bigint(30) NOT NULL COMMENT 'Cedula Hoja de vida',
  `Nombres` varchar(50) DEFAULT NULL,
  `Apellidos` varchar(50) DEFAULT NULL,
  `FechIngr` date DEFAULT NULL COMMENT 'Fecha de ingreso de la Hoja de Vida',
  `AreaAd1` varchar(200) DEFAULT NULL COMMENT 'Area administrativa que aspira 1',
  `AreaAd2` varchar(200) DEFAULT NULL COMMENT 'Area administrativa que aspira 2',
  `AreaAd3` varchar(200) DEFAULT NULL COMMENT 'Area administrativa que aspira 3',
  `AreaAd4` varchar(200) DEFAULT NULL COMMENT 'Area administrativa que aspira 4',
  `AreaAd5` varchar(200) DEFAULT NULL COMMENT 'Area administrativa que aspira 5',
  `Facult1` varchar(200) DEFAULT NULL COMMENT 'Facultad a la que aspira 1',
  `Facult2` varchar(200) DEFAULT NULL COMMENT 'Facultad a la que aspira 2',
  `Facult3` varchar(200) DEFAULT NULL COMMENT 'Facultad a la que aspira 3',
  `Facult4` varchar(200) DEFAULT NULL COMMENT 'Facultad a la que aspira 4',
  `Facult5` varchar(200) DEFAULT NULL COMMENT 'Facultad a la que aspira 5',
  `CargoAd1` varchar(200) DEFAULT NULL COMMENT 'Cargo administrativo que aspira 1',
  `CargoAd2` varchar(200) DEFAULT NULL COMMENT 'Cargo administrativo que aspira 2',
  `CargoAd3` varchar(200) DEFAULT NULL COMMENT 'Cargo administrativo que aspira 3',
  `CargoAd4` varchar(200) DEFAULT NULL COMMENT 'Cargo administrativo que aspira 4',
  `CargoAd5` varchar(200) DEFAULT NULL COMMENT 'Cargo administrativo que aspira 5',
  `Asignat1` varchar(200) DEFAULT NULL COMMENT 'Asignatura a la que aspira 1',
  `Asignat2` varchar(200) DEFAULT NULL COMMENT 'Asignatura a la que aspira 2',
  `Asignat3` varchar(200) DEFAULT NULL COMMENT 'Asignatura a la que aspira 3',
  `Asignat4` varchar(200) DEFAULT NULL COMMENT 'Asignatura a la que aspira 4',
  `Asignat5` varchar(200) DEFAULT NULL COMMENT 'Asignatura a la que aspira 5',
  `Sexo` varchar(20) DEFAULT NULL,
  `EstCivil` varchar(20) DEFAULT NULL,
  `Edad` int(11) DEFAULT NULL,
  `Nacional` varchar(30) DEFAULT NULL COMMENT 'Nacionalidad',
  `FechaNac` date DEFAULT NULL COMMENT 'Fecha de nacimiento',
  `LugarNac` varchar(50) DEFAULT NULL,
  `LibrMili` int(11) DEFAULT NULL COMMENT 'Libreta Mil. No',
  `Distrito` varchar(30) DEFAULT NULL COMMENT 'Distrito libreta militar',
  `Clase` varchar(20) DEFAULT NULL COMMENT 'Clase libreta militar',
  `FechaExp` date DEFAULT NULL COMMENT 'Fecha expedicion tarjeta militar',
  `Pasaport` varchar(30) DEFAULT NULL COMMENT 'No de pasaporte',
  `Profesion` varchar(100) DEFAULT NULL,
  `MatrProf` varchar(50) DEFAULT NULL COMMENT 'Matricula profesional No',
  `MatrDe` varchar(50) DEFAULT NULL COMMENT 'de donde es la Matricula prof',
  `FondPens` varchar(200) DEFAULT NULL COMMENT 'Fondo de pensiones',
  `EPS` varchar(200) DEFAULT NULL,
  `GrupoSan` varchar(3) DEFAULT NULL COMMENT 'Grupo sanguineo',
  `Direccion` varchar(200) DEFAULT NULL,
  `Barrio` varchar(50) DEFAULT NULL,
  `Telefono` varchar(50) DEFAULT NULL,
  `Celular` varchar(50) DEFAULT NULL,
  `Email` varchar(255) DEFAULT NULL,
  `AvisarA` varchar(255) DEFAULT NULL COMMENT 'En caso de Emergencia avisar a ',
  `TelAvis` varchar(50) DEFAULT NULL COMMENT 'Telefono persona a la que se avisa',
  `PadresVi` varchar(255) DEFAULT NULL COMMENT 'Nombres de padres vivos',
  `Conyuge` varchar(200) DEFAULT NULL COMMENT 'Nombre conyuge',
  `OcupCony` varchar(200) DEFAULT NULL COMMENT 'Ocupacion conyuge',
  `NoHijos` int(11) DEFAULT NULL COMMENT 'Numero de hijos',
  `NombHij1` varchar(200) DEFAULT NULL COMMENT 'Nombre hijo 1',
  `NombHij2` varchar(200) DEFAULT NULL COMMENT 'Nombre hijo 2',
  `NombHij3` varchar(200) DEFAULT NULL COMMENT 'Nombre hijo 3',
  `NombHij4` varchar(200) DEFAULT NULL COMMENT 'Nombre hijo 4',
  `NombHij5` varchar(200) DEFAULT NULL COMMENT 'Nombre hijo 5',
  `FeNaHij1` date DEFAULT NULL COMMENT 'Fecha nacimiento hijo 1',
  `FeNaHij2` date DEFAULT NULL COMMENT 'Fecha nacimiento hijo 2',
  `FeNaHij3` date DEFAULT NULL COMMENT 'Fecha nacimiento hijo 3',
  `FeNaHij4` date DEFAULT NULL COMMENT 'Fecha nacimiento hijo 4',
  `FeNaHij5` date DEFAULT NULL COMMENT 'Fecha nacimiento hijo 5',
  `IdenHij1` bigint(30) DEFAULT NULL COMMENT 'Identificacion hijo 1',
  `IdenHij2` bigint(30) DEFAULT NULL COMMENT 'Identificacion hijo 2',
  `IdenHij3` bigint(30) DEFAULT NULL COMMENT 'Identificacion hijo 3',
  `IdenHij4` bigint(30) DEFAULT NULL COMMENT 'Identificacion hijo 4',
  `IdenHij5` bigint(30) DEFAULT NULL COMMENT 'Identificacion hijo 5',
  `EdadHij1` int(11) DEFAULT NULL COMMENT 'Edad hijo 1',
  `EdadHij2` int(11) DEFAULT NULL COMMENT 'Edad hijo 2',
  `EdadHij3` int(11) DEFAULT NULL COMMENT 'Edad hijo 3',
  `EdadHij4` int(11) DEFAULT NULL COMMENT 'Edad hijo 4',
  `EdadHij5` int(11) DEFAULT NULL COMMENT 'Edad hijo 5',
  `UnEdHij1` varchar(20) DEFAULT NULL COMMENT 'años/meses hijo 1',
  `UnEdHij2` varchar(20) DEFAULT NULL COMMENT 'años/meses hijo 2',
  `UnEdHij3` varchar(20) DEFAULT NULL COMMENT 'años/meses hijo 3',
  `UnEdHij4` varchar(20) DEFAULT NULL COMMENT 'años/meses hijo 4',
  `UnEdHij5` varchar(20) DEFAULT NULL COMMENT 'años/meses hijo 5',
  `SexoHij1` varchar(20) DEFAULT NULL COMMENT 'Sexo hijo 1',
  `SexoHij2` varchar(20) DEFAULT NULL COMMENT 'Sexo hijo 2',
  `SexoHij3` varchar(20) DEFAULT NULL COMMENT 'Sexo hijo 3',
  `SexoHij4` varchar(20) DEFAULT NULL COMMENT 'Sexo hijo 4',
  `SexoHij5` varchar(20) DEFAULT NULL COMMENT 'Sexo hijo 5',
  `Titulo1` varchar(255) DEFAULT NULL COMMENT 'Estudios realizados - Titulo 1',
  `Titulo2` varchar(255) DEFAULT NULL COMMENT 'Estudios realizados - Titulo 2',
  `Titulo3` varchar(255) DEFAULT NULL COMMENT 'Estudios realizados - Titulo 3',
  `Titulo4` varchar(255) DEFAULT NULL COMMENT 'Estudios realizados - Titulo 4',
  `Titulo5` varchar(255) DEFAULT NULL COMMENT 'Estudios realizados - Titulo 5',
  `Titulo6` varchar(255) DEFAULT NULL COMMENT 'Estudios realizados - Titulo 6',
  `Titulo7` varchar(255) DEFAULT NULL COMMENT 'Estudios realizados - Titulo 7',
  `NivelT1` varchar(30) DEFAULT NULL COMMENT 'Nivel del Titulo 1',
  `NivelT2` varchar(30) DEFAULT NULL COMMENT 'Nivel del Titulo 2',
  `NivelT3` varchar(30) DEFAULT NULL COMMENT 'Nivel del Titulo 3',
  `NivelT4` varchar(30) DEFAULT NULL COMMENT 'Nivel del Titulo 4',
  `NivelT5` varchar(30) DEFAULT NULL COMMENT 'Nivel del Titulo 5',
  `NivelT6` varchar(30) DEFAULT NULL COMMENT 'Nivel del Titulo 6',
  `NivelT7` varchar(30) DEFAULT NULL COMMENT 'Nivel del Titulo 7',
  `Instit1` varchar(255) DEFAULT NULL COMMENT 'Institucion Titulo 1',
  `Instit2` varchar(255) DEFAULT NULL COMMENT 'Institucion Titulo 2',
  `Instit3` varchar(255) DEFAULT NULL COMMENT 'Institucion Titulo 3',
  `Instit4` varchar(255) DEFAULT NULL COMMENT 'Institucion Titulo 4',
  `Instit5` varchar(255) DEFAULT NULL COMMENT 'Institucion Titulo 5',
  `Instit6` varchar(255) DEFAULT NULL COMMENT 'Institucion Titulo 6',
  `Instit7` varchar(255) DEFAULT NULL COMMENT 'Institucion Titulo 7',
  `CiudaT1` varchar(50) DEFAULT NULL COMMENT 'Ciudad Titulo 1',
  `CiudaT2` varchar(50) DEFAULT NULL COMMENT 'Ciudad Titulo 2',
  `CiudaT3` varchar(50) DEFAULT NULL COMMENT 'Ciudad Titulo 3',
  `CiudaT4` varchar(50) DEFAULT NULL COMMENT 'Ciudad Titulo 4',
  `CiudaT5` varchar(50) DEFAULT NULL COMMENT 'Ciudad Titulo 5',
  `CiudaT6` varchar(50) DEFAULT NULL COMMENT 'Ciudad Titulo 6',
  `CiudaT7` varchar(50) DEFAULT NULL COMMENT 'Ciudad Titulo 7',
  `FechaT1` date DEFAULT NULL COMMENT 'Fecha terminacion Titulo 1',
  `FechaT2` date DEFAULT NULL COMMENT 'Fecha terminacion Titulo 2',
  `FechaT3` date DEFAULT NULL COMMENT 'Fecha terminacion Titulo 3',
  `FechaT4` date DEFAULT NULL COMMENT 'Fecha terminacion Titulo 4',
  `FechaT5` date DEFAULT NULL COMMENT 'Fecha terminacion Titulo 5',
  `FechaT6` date DEFAULT NULL COMMENT 'Fecha terminacion Titulo 6',
  `FechaT7` date DEFAULT NULL COMMENT 'Fecha terminacion Titulo 7',
  `EstudAct` varchar(2) DEFAULT NULL COMMENT 'Estudia actualmente SI/NO',
  `Program1` varchar(255) DEFAULT NULL COMMENT 'Estudia actualmente - Programa 1',
  `Program2` varchar(255) DEFAULT NULL COMMENT 'Estudia actualmente - Programa 2',
  `Program3` varchar(255) DEFAULT NULL COMMENT 'Estudia actualmente - Programa 3',
  `Program4` varchar(255) DEFAULT NULL COMMENT 'Estudia actualmente - Programa 4',
  `Program5` varchar(255) DEFAULT NULL COMMENT 'Estudia actualmente - Programa 5',
  `Semestr1` int(11) DEFAULT NULL COMMENT 'Semestre actual 1',
  `Semestr2` int(11) DEFAULT NULL COMMENT 'Semestre actual 2',
  `Semestr3` int(11) DEFAULT NULL COMMENT 'Semestre actual 3',
  `Semestr4` int(11) DEFAULT NULL COMMENT 'Semestre actual 4',
  `Semestr5` int(11) DEFAULT NULL COMMENT 'Semestre actual 5',
  `InstAct1` varchar(255) DEFAULT NULL COMMENT 'Institucion actual 1',
  `InstAct2` varchar(255) DEFAULT NULL COMMENT 'Institucion actual 2',
  `InstAct3` varchar(255) DEFAULT NULL COMMENT 'Institucion actual 3',
  `InstAct4` varchar(255) DEFAULT NULL COMMENT 'Institucion actual 4',
  `InstAct5` varchar(255) DEFAULT NULL COMMENT 'Institucion actual 5',
  `Horario1` varchar(20) DEFAULT NULL COMMENT 'Horario actual 1 - Diurno/Nocturno',
  `Horario2` varchar(20) DEFAULT NULL COMMENT 'Horario actual 2 - Diurno/Nocturno',
  `Horario3` varchar(20) DEFAULT NULL COMMENT 'Horario actual 3 - Diurno/Nocturno',
  `Horario4` varchar(20) DEFAULT NULL COMMENT 'Horario actual 4 - Diurno/Nocturno',
  `Horario5` varchar(20) DEFAULT NULL COMMENT 'Horario actual 5 - Diurno/Nocturno',
  `PrVirDi1` varchar(20) DEFAULT NULL COMMENT 'Presencial / Virtual /Distancia 1',
  `PrVirDi2` varchar(20) DEFAULT NULL COMMENT 'Presencial / Virtual /Distancia 2',
  `PrVirDi3` varchar(20) DEFAULT NULL COMMENT 'Presencial / Virtual /Distancia 3',
  `PrVirDi4` varchar(20) DEFAULT NULL COMMENT 'Presencial / Virtual /Distancia 4',
  `PrVirDi5` varchar(20) DEFAULT NULL COMMENT 'Presencial / Virtual /Distancia 5',
  `Software1` varchar(100) DEFAULT NULL COMMENT 'Que software o programas de Computación Maneja 1',
  `Software2` varchar(100) DEFAULT NULL COMMENT 'Que software o programas de Computación Maneja 2',
  `Software3` varchar(100) DEFAULT NULL COMMENT 'Que software o programas de Computación Maneja 3',
  `Software4` varchar(100) DEFAULT NULL COMMENT 'Que software o programas de Computación Maneja 4',
  `Software5` varchar(100) DEFAULT NULL COMMENT 'Que software o programas de Computación Maneja 5',
  `Idioma1` varchar(30) DEFAULT NULL COMMENT 'Que Idioma extranjero domina 1',
  `Idioma2` varchar(30) DEFAULT NULL COMMENT 'Que Idioma extranjero domina 2',
  `Idioma3` varchar(30) DEFAULT NULL COMMENT 'Que Idioma extranjero domina 3',
  `Idioma4` varchar(30) DEFAULT NULL COMMENT 'Que Idioma extranjero domina 4',
  `Idioma5` varchar(30) DEFAULT NULL COMMENT 'Que Idioma extranjero domina 5',
  `Entidad1` varchar(255) DEFAULT NULL COMMENT 'Experiencia laboral - Entidad 1',
  `Entidad2` varchar(255) DEFAULT NULL COMMENT 'Experiencia laboral - Entidad 2',
  `Entidad3` varchar(255) DEFAULT NULL COMMENT 'Experiencia laboral - Entidad 3',
  `Entidad4` varchar(255) DEFAULT NULL COMMENT 'Experiencia laboral - Entidad 4',
  `Entidad5` varchar(255) DEFAULT NULL COMMENT 'Experiencia laboral - Entidad 5',
  `Entidad6` varchar(255) DEFAULT NULL COMMENT 'Experiencia laboral - Entidad 6',
  `Entidad7` varchar(255) DEFAULT NULL COMMENT 'Experiencia laboral - Entidad 7',
  `CargoOc1` varchar(200) DEFAULT NULL COMMENT 'Experiencia laboral - Cargo 1',
  `CargoOc2` varchar(200) DEFAULT NULL COMMENT 'Experiencia laboral - Cargo 2',
  `CargoOc3` varchar(200) DEFAULT NULL COMMENT 'Experiencia laboral - Cargo 3',
  `CargoOc4` varchar(200) DEFAULT NULL COMMENT 'Experiencia laboral - Cargo 4',
  `CargoOc5` varchar(200) DEFAULT NULL COMMENT 'Experiencia laboral - Cargo 5',
  `CargoOc6` varchar(200) DEFAULT NULL COMMENT 'Experiencia laboral - Cargo 6',
  `CargoOc7` varchar(200) DEFAULT NULL COMMENT 'Experiencia laboral - Cargo 7',
  `TelEnti1` varchar(100) DEFAULT NULL COMMENT 'Telefonos Entidad 1',
  `TelEnti2` varchar(100) DEFAULT NULL COMMENT 'Telefonos Entidad 2',
  `TelEnti3` varchar(100) DEFAULT NULL COMMENT 'Telefonos Entidad 3',
  `TelEnti4` varchar(100) DEFAULT NULL COMMENT 'Telefonos Entidad 4',
  `TelEnti5` varchar(100) DEFAULT NULL COMMENT 'Telefonos Entidad 5',
  `TelEnti6` varchar(100) DEFAULT NULL COMMENT 'Telefonos Entidad 6',
  `TelEnti7` varchar(100) DEFAULT NULL COMMENT 'Telefonos Entidad 7',
  `DirEnti1` varchar(255) DEFAULT NULL COMMENT 'Direccion Entidad 1',
  `DirEnti2` varchar(255) DEFAULT NULL COMMENT 'Direccion Entidad 2',
  `DirEnti3` varchar(255) DEFAULT NULL COMMENT 'Direccion Entidad 3',
  `DirEnti4` varchar(255) DEFAULT NULL COMMENT 'Direccion Entidad 4',
  `DirEnti5` varchar(255) DEFAULT NULL COMMENT 'Direccion Entidad 5',
  `DirEnti6` varchar(255) DEFAULT NULL COMMENT 'Direccion Entidad 6',
  `DirEnti7` varchar(255) DEFAULT NULL COMMENT 'Direccion Entidad 7',
  `JefeInm1` varchar(100) DEFAULT NULL COMMENT 'Jefe Inmediato 1',
  `JefeInm2` varchar(100) DEFAULT NULL COMMENT 'Jefe Inmediato 2',
  `JefeInm3` varchar(100) DEFAULT NULL COMMENT 'Jefe Inmediato 3',
  `JefeInm4` varchar(100) DEFAULT NULL COMMENT 'Jefe Inmediato 4',
  `JefeInm5` varchar(100) DEFAULT NULL COMMENT 'Jefe Inmediato 5',
  `JefeInm6` varchar(100) DEFAULT NULL COMMENT 'Jefe Inmediato 6',
  `JefeInm7` varchar(100) DEFAULT NULL COMMENT 'Jefe Inmediato 7',
  `MotiRet1` varchar(255) DEFAULT NULL COMMENT 'Motivo Retiro 1',
  `MotiRet2` varchar(255) DEFAULT NULL COMMENT 'Motivo Retiro 2',
  `MotiRet3` varchar(255) DEFAULT NULL COMMENT 'Motivo Retiro 3',
  `MotiRet4` varchar(255) DEFAULT NULL COMMENT 'Motivo Retiro 4',
  `MotiRet5` varchar(255) DEFAULT NULL COMMENT 'Motivo Retiro 5',
  `MotiRet6` varchar(255) DEFAULT NULL COMMENT 'Motivo Retiro 6',
  `MotiRet7` varchar(255) DEFAULT NULL COMMENT 'Motivo Retiro 7',
  PRIMARY KEY (`CCHojaVi`)
) ENGINE=MyISAM DEFAULT CHARSET=latin1;

/*Data for the table `thvsolicit_copy2` */

/*!40101 SET SQL_MODE=@OLD_SQL_MODE */;
/*!40014 SET FOREIGN_KEY_CHECKS=@OLD_FOREIGN_KEY_CHECKS */;
/*!40014 SET UNIQUE_CHECKS=@OLD_UNIQUE_CHECKS */;
/*!40111 SET SQL_NOTES=@OLD_SQL_NOTES */;
