var i18n = $.extend({}, i18n || {}, { 
    xgcalendar: {
        dateformat: {
            "fulldaykey": "MMddyyyy",
            "fulldayshow": "L d yyyy",
            "fulldayvalue": "M/d/yyyy",
            "Md": "W M/d",
            "Md3": "L d",
            "separator": "/",
            "year_index": 2,
            "month_index": 0,
            "day_index": 1,
            "day": "d",
            "sun": "Dom",
            "mon": "&#76;un",
            "tue": "Mar",
            "wed": "Mie",
            "thu": "Jue",
            "fri": "Vie",
            "sat": "Sáb",
            "jan": "Ene",
            "feb": "Feb",
            "mar": "Mar",
            "apr": "Abr",
            "may": "May",
            "jun": "Jun",
            "jul": "Jul",
            "aug": "Ago",
            "sep": "Sep",
            "oct": "Oct",
            "nov": "Nov",
            "dec": "Dic"
        },
        "no_implemented": "No implementado aún",
        "to_date_view": "Clic para ver la fecha actual",
        "i_undefined": "Sin definir",
        "allday_event": "Actividad de todo el día",
        "repeat_event": "Repetir actividad",
        "time": "Hora",
        "event": "Actividad",
        "location": "Lugar",
        "participant": "Participante",
        "get_data_exception": "Excepción al obtener los datos",
        "new_event": "Nueva actividad",
        "confirm_delete_event": "¿Realmente deseas eliminar esta actividad?",
        "confrim_delete_event_or_all": "¿Quieres que todos repitan actividad o solo esta actividad? \r\nPresiona [OK] para eliminar esta actividad, presiona [Cancel] para borrar todas las actividades",
        "data_format_error": "Error de formato de los datos! ",
        "invalid_title": "Titulo de la actividad no puede ser vacio o contener ($<>)",
        "view_no_ready": "La vista no está lista",
        "example": "e.j., reunión en cuarto 107",
        "content": "Que",
        "create_event": "Crear actividad",
        "update_detail": "Editar detalles",
        "click_to_detail": "Ver detalles",
        "i_delete": "Eliminar",
        "day_plural": "días",
        "others": "Otros",
        "item": ""
    }
});
